FROM ruby:2.6.3-alpine                                                                                                                                                                   
RUN apk update && apk upgrade
